// Seed data for Madras Menu Studio.
// Source: dishes pulled from the catering company's own menu documents,
// plus additional coverage items added so every cuisine has enough dishes
// per meal/category to avoid empty or degenerate menu-generation results.
//
// item shape:
// { name, category, cuisines:[...], veg:bool, meals:[...], events:[...],
//   religions:[...] (omit = all), repeatable:bool }

const ALL_EVENTS = ['wedding','sangeet','welcome','mehndi','breakfast','latenight','sweet16','anniversary','birthday','lunch','cocktail','dinner','baraat','ceremony'];
const ALL_REL = ['hindu','muslim','christian'];

function I(name, category, cuisines, veg, meals, events, religions, repeatable) {
  return { name, category, cuisines, veg, meals, events, religions: religions || ALL_REL, repeatable: !!repeatable };
}

const items = [
/* ================= BREAKFAST ================= */
I('Freshly Made Bombay Sandwiches (Eggless Bread)','breakfast',['North Indian'],true,['breakfast'],['breakfast','welcome','wedding']),
I('Kancheepuram Idli with Mysore Chutney','breakfast',['South Indian','Tamil'],true,['breakfast','lunch'],['breakfast','wedding','welcome']),
I('Poha Display','breakfast',['North Indian','Marathi'],true,['breakfast'],['breakfast']),
I('Live Dosa Station — Mysore, Plain, Masala','breakfast',['South Indian','Tamil'],true,['breakfast'],['breakfast','wedding']),
I('Daal Pakwan with Sweet & Green Chutney','breakfast',['Sindhi'],true,['breakfast'],['breakfast']),
I('Masala Cheese Sandwiches','breakfast',['North Indian'],true,['breakfast'],['breakfast']),
I('Vegetable Uppma with Chutneys','breakfast',['South Indian','Tamil','Telugu/Andhra'],true,['breakfast'],['breakfast']),
I('Homemade Yogurt in Mud Pots','breakfast',['North Indian'],true,['breakfast'],['breakfast','wedding']),
I('Happy Poha with Choice of Chutneys','breakfast',['Marathi'],true,['breakfast'],['breakfast']),
I('Jaipuri Paneer Wraps','breakfast',['North Indian','Punjabi'],true,['breakfast'],['breakfast']),
I('Vada Pav with Condiments Station','breakfast',['Marathi'],true,['breakfast'],['breakfast']),
I('North Indian Live Omelet / Masala Omelet Station','breakfast',['North Indian'],false,['breakfast'],['breakfast','wedding'],['hindu','christian']),
I('Ven Pongal with Sambar','breakfast',['South Indian','Tamil'],true,['breakfast'],['breakfast']),
I('Bengali Luchi with Aloo Dum','breakfast',['Bangladeshi'],true,['breakfast'],['breakfast']),
I('Khaman Dhokla Breakfast Display','breakfast',['Gujarati'],true,['breakfast'],['breakfast']),
I('Continental Pastry & Fresh Fruit Display','breakfast',['American'],true,['breakfast'],['breakfast','welcome']),
// Telugu/Andhra breakfast coverage
I('Pesarattu (Green Gram Dosa) with Allam Chutney','breakfast',['Telugu/Andhra'],true,['breakfast'],['breakfast']),
I('Upma Rava, Andhra Style with Curry Leaf Tempering','breakfast',['Telugu/Andhra'],true,['breakfast'],['breakfast']),
I('Attu (Andhra Dosa) with Karam Podi','breakfast',['Telugu/Andhra'],true,['breakfast'],['breakfast']),
I('Idli with Andhra Tomato Pachadi','breakfast',['Telugu/Andhra'],true,['breakfast'],['breakfast']),
// Kerala breakfast
I('Appam with Kerala Vegetable Stew','breakfast',['Kerala'],true,['breakfast'],['breakfast']),
I('Puttu with Kadala Curry','breakfast',['Kerala'],true,['breakfast'],['breakfast']),
I('Kerala Egg Roast Breakfast Bowl','breakfast',['Kerala'],false,['breakfast'],['breakfast'],['hindu','christian']),
// Punjabi breakfast
I('Amritsari Aloo Kulcha with Chole','breakfast',['Punjabi'],true,['breakfast'],['breakfast']),
I('Stuffed Paratha Bar — Aloo, Gobi, Paneer','breakfast',['Punjabi'],true,['breakfast'],['breakfast']),
// Gujarati breakfast
I('Handvo with Green Chutney','breakfast',['Gujarati'],true,['breakfast'],['breakfast']),
I('Thepla with Curd & Pickle','breakfast',['Gujarati'],true,['breakfast'],['breakfast']),
// Sindhi breakfast
I('Sindhi Koki with Yogurt','breakfast',['Sindhi'],true,['breakfast'],['breakfast']),
// Marathi breakfast
I('Misal Pav with Farsan Topping','breakfast',['Marathi'],true,['breakfast'],['breakfast']),
I('Sabudana Khichdi','breakfast',['Marathi'],true,['breakfast'],['breakfast']),
// Pakistani breakfast
I('Halwa Puri with Chana Masala','breakfast',['Pakistani'],true,['breakfast'],['breakfast']),
I('Lahori Paye (slow-cooked trotters)','breakfast',['Pakistani'],false,['breakfast'],['breakfast'],['muslim']),
// Bangladeshi breakfast
I('Bhuna Khichuri with Beguni','breakfast',['Bangladeshi'],true,['breakfast'],['breakfast']),
// Tamil breakfast
I('Pongal Bar — Ven Pongal & Sakkarai Pongal','breakfast',['Tamil'],true,['breakfast'],['breakfast']),
I('Adai with Avial','breakfast',['Tamil'],true,['breakfast'],['breakfast']),
// Fusion/American/Chinese/Mexican/Italian/Mediterranean breakfast
I('Congee Breakfast Bar with Scallion & Chili Oil','breakfast',['Chinese'],true,['breakfast'],['breakfast']),
I('Huevos Rancheros Station','breakfast',['Mexican'],false,['breakfast'],['breakfast'],['hindu','christian']),
I('Frittata Bar with Roasted Vegetables','breakfast',['Italian'],false,['breakfast'],['breakfast'],['hindu','christian']),
I('Shakshuka with Warm Pita','breakfast',['Mediterranean'],false,['breakfast'],['breakfast'],['hindu','muslim','christian']),
I('Belgian Waffle & Pancake Bar','breakfast',['American'],true,['breakfast'],['breakfast','sweet16']),
I('Masala Chai French Toast','breakfast',['Fusion'],true,['breakfast'],['breakfast']),

/* ================= STARTERS / CHAAT / HORS D'OEUVRE ================= */
I('Assorted Chaat Station Display','starter',['North Indian'],true,['snacks','lunch','dinner'],['mehndi','sangeet','wedding','welcome']),
I('Papdi Chaat with Chaat & Sev','starter',['North Indian','Punjabi'],true,['snacks','lunch'],['mehndi','sangeet','wedding']),
I('Bhel Poori / Pani Poori Station','starter',['North Indian'],true,['snacks','cocktail'],['mehndi','sangeet','wedding']),
I('Freshly Made Chole & Batura Live','starter',['Punjabi'],true,['snacks','lunch'],['mehndi','sangeet','wedding']),
I('Dahi Bhalla with Roasted Cumin & Ginger','starter',['North Indian'],true,['snacks','cocktail'],['mehndi','sangeet','wedding']),
I('Sev Puri','starter',['North Indian'],true,['snacks','cocktail'],['mehndi','sangeet','wedding']),
I('Samosa Choley Chaat on Tawa','starter',['North Indian','Punjabi'],true,['snacks'],['mehndi','sangeet']),
I('Kachori Lilva with Assorted Chutneys','starter',['Gujarati'],true,['snacks','lunch'],['mehndi','sangeet','wedding']),
I('Hara Chicken Kebabs','starter',['North Indian'],false,['snacks','cocktail'],['mehndi','sangeet','wedding'],['hindu','christian']),
I('Cocktail Vegetable Samosas with Chutneys','starter',['North Indian'],true,['cocktail','snacks'],['wedding','cocktail','sangeet','mehndi']),
I('Hand Rolled Masala Paneer & Spinach Puffs','starter',['Fusion'],true,['cocktail'],['wedding','cocktail']),
I('Stuffed Chili Poppers with Wasabi-Mint Fusion','starter',['Fusion'],true,['cocktail'],['wedding','cocktail']),
I('Tangy Chaat Shooters with Bhel & Tamarind Drizzle','starter',['North Indian'],true,['cocktail'],['wedding','cocktail']),
I('Chili Garlic Shrimp','starter',['Fusion','South Indian'],false,['cocktail'],['wedding','cocktail'],['hindu','christian']),
I('Tandoori Grilled Baby Lamb Chops','starter',['North Indian'],false,['cocktail'],['wedding','cocktail']),
I('Chicken 65 Butler-Passed in Bamboo Cones','starter',['South Indian','Telugu/Andhra'],false,['cocktail'],['wedding','cocktail']),
I('Crispy Spring Rolls with Sweet & Hot Chili Sauce','starter',['Chinese'],true,['cocktail','snacks'],['wedding','cocktail']),
I('Manchurian Kati Roll (mini)','starter',['Chinese','Fusion'],true,['cocktail'],['wedding','cocktail']),
I('Jaipuri Paneer Kati Roll (mini)','starter',['North Indian'],true,['cocktail'],['wedding','cocktail']),
I('Chicken Tikka Kati Roll (mini)','starter',['North Indian'],false,['cocktail'],['wedding','cocktail']),
I('Gobi Manchurian Dry with Curry Leaves','starter',['Chinese','South Indian'],true,['cocktail','snacks'],['wedding','cocktail','mehndi']),
I('Shrimp Shashlik with Roasted Pepper & Onion','starter',['Mediterranean','Fusion'],false,['cocktail'],['wedding','cocktail'],['hindu','christian']),
I('Fish Pakora with Tandoori Tartar','starter',['Kerala'],false,['cocktail','snacks'],['wedding','cocktail'],['hindu','christian']),
I('Tandoori Chicken Chops','starter',['North Indian'],false,['cocktail'],['wedding','cocktail']),
I('Mini Masala Sliders (Eggless Buns)','starter',['Fusion','American'],true,['cocktail','ceremony'],['wedding','cocktail']),
I('Cocktail Khaman Dhokla with Chutney Drizzle','starter',['Gujarati'],true,['cocktail','ceremony'],['wedding','cocktail']),
I('Badami Paneer Roll with Pudhina Chutney','starter',['North Indian'],true,['ceremony','cocktail'],['ceremony','wedding']),
I('Roasted Red Pepper Hummus with Pita Chips','starter',['Mediterranean'],true,['cocktail','snacks'],['wedding','cocktail']),
I('Indian Falafel with Tahini Drizzle','starter',['Mediterranean','Fusion'],true,['cocktail','snacks'],['wedding','cocktail']),
I('Greek Farmer Salad with Feta & Olives','starter',['Mediterranean'],true,['lunch','dinner','cocktail'],['wedding','dinner','cocktail']),
I('Boutique Taco Station Display','starter',['Mexican'],true,['cocktail','snacks'],['wedding','cocktail','sweet16']),
I('Nacho Bar with Guacamole & Pico de Gallo','starter',['Mexican'],true,['cocktail','snacks'],['wedding','cocktail','sweet16']),
I('California Mixed Greens with Cucumber & Tomato','starter',['American'],true,['lunch','dinner'],['wedding','dinner','anniversary']),
I('Vegetable Crudités with Assorted Dips','starter',['American'],true,['cocktail'],['wedding','cocktail','anniversary']),
I('Fresh Fruit & Cheese Display','starter',['American'],true,['cocktail'],['wedding','cocktail','anniversary','birthday']),
I('Classic Caesar with Mango & Banana-Bread Croutons','starter',['Italian','Fusion'],true,['lunch','dinner'],['wedding','dinner']),
I('Mirchi Bajji (Andhra Chili Fritters)','starter',['Telugu/Andhra'],true,['snacks'],['mehndi','sangeet']),
I('Gongura Chicken Fry (starter portion)','starter',['Telugu/Andhra'],false,['cocktail','snacks'],['wedding','cocktail']),
I('Bandar Laddu Savory Cousin — Punugulu','starter',['Telugu/Andhra'],true,['snacks'],['mehndi','sangeet']),
I('Karachi Chicken Boti Kebab','starter',['Pakistani'],false,['cocktail'],['wedding','cocktail'],['muslim']),
I('Bihari Kebab Skewers','starter',['Pakistani','North Indian'],false,['cocktail'],['wedding','cocktail'],['muslim','hindu']),
I('Sindhi Papad Chaat','starter',['Sindhi'],true,['snacks'],['mehndi','sangeet']),
I('Batata Vada, Mumbai Style','starter',['Marathi'],true,['snacks'],['mehndi','sangeet']),
I('Fish Fry, Bengali Style','starter',['Bangladeshi'],false,['cocktail','snacks'],['wedding','cocktail'],['hindu','muslim','christian']),
I('Shingara (Bengali Samosa)','starter',['Bangladeshi'],true,['snacks'],['mehndi','sangeet']),

/* ================= MAINS ================= */
I('Butter Chicken','main',['North Indian','Punjabi'],false,['lunch','dinner'],['wedding','dinner','sangeet','anniversary'],['hindu','christian']),
I('Chicken Tikka Masala','main',['North Indian','Punjabi'],false,['lunch','dinner'],['wedding','dinner','anniversary'],['hindu','christian']),
I('Lamb Rogan Josh','main',['North Indian','Pakistani'],false,['lunch','dinner'],['wedding','dinner']),
I('Saag Paneer','main',['North Indian','Punjabi'],true,['lunch','dinner'],['wedding','dinner','sangeet','anniversary','birthday']),
I('Navrathan Korma','main',['North Indian'],true,['lunch','dinner'],['wedding','dinner','anniversary']),
I('Vegetable Korma','main',['North Indian'],true,['lunch','dinner'],['wedding','dinner']),
I('Punjabi Chole','main',['Punjabi'],true,['lunch','dinner'],['wedding','lunch','sangeet']),
I('Masala Bhindi (no onion)','main',['Gujarati','North Indian'],true,['lunch','dinner'],['wedding','lunch']),
I('Baingan ka Bharta','main',['North Indian'],true,['lunch','dinner'],['wedding','dinner']),
I('Gobi Matar Masala','main',['North Indian'],true,['lunch','dinner'],['wedding','lunch','dinner']),
I('Tandoori Mixed Grill — Chicken Tikka, Malai Kebab, Lamb Seekh','main',['North Indian'],false,['dinner'],['wedding','dinner']),
I('Grilled Fish Malabar','main',['Kerala'],false,['lunch','dinner'],['wedding','dinner'],['hindu','christian']),
I('Chicken Madras','main',['South Indian','Tamil'],false,['lunch','dinner'],['wedding','dinner']),
I('Kallu Shapp Beef Ularthiyathu','main',['Kerala'],false,['dinner'],['dinner'],['christian']),
I('Mutta (Egg) Roast','main',['Kerala'],false,['breakfast','lunch','dinner'],['breakfast','dinner'],['hindu','christian']),
I('Saag Methi Corn Paneer','main',['North Indian','Fusion'],true,['lunch','dinner'],['wedding','dinner']),
I('Sai Bhaji','main',['Sindhi'],true,['lunch','dinner'],['wedding','lunch']),
I('Tindoora Subji','main',['Sindhi','South Indian'],true,['lunch','dinner'],['wedding','lunch']),
I('Vegetable Kolhapuri','main',['Marathi'],true,['lunch','dinner'],['wedding','dinner']),
I('Sindhi Aloo Tuk','main',['Sindhi'],true,['lunch','dinner'],['wedding','lunch']),
I('Undhyu','main',['Gujarati'],true,['lunch','dinner'],['wedding','lunch']),
I('Kadhi (Gujarati style)','main',['Gujarati'],true,['lunch'],['wedding','lunch']),
I('Dal Fry','main',['North Indian'],true,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Potato Korma','main',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Gutti Vengaya (Stuffed Baby Eggplant)','main',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Fried Okra, Andhra Style','main',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Tomato Pappu with Ghee','main',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Rasam','main',['South Indian','Tamil'],true,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Chicken 65 with Southern Spices','main',['South Indian','Telugu/Andhra'],false,['lunch','dinner'],['wedding','dinner']),
I('Kozhikoden Mutton Biryani','main',['Kerala'],false,['lunch','dinner'],['wedding','dinner']),
I('Thalassery Chicken Biryani','main',['Kerala'],false,['lunch','dinner'],['wedding','dinner']),
I('Gongura Mutton Curry','main',['Telugu/Andhra'],false,['lunch','dinner'],['wedding','dinner']),
I('Andhra Chicken Curry','main',['Telugu/Andhra'],false,['lunch','dinner'],['wedding','dinner']),
I('Pesarattu Upma Combo Plate','main',['Telugu/Andhra'],true,['breakfast','lunch'],['breakfast']),
I('Karahi Gosht','main',['Pakistani'],false,['lunch','dinner'],['wedding','dinner'],['muslim']),
I('Nihari (slow-cooked stew)','main',['Pakistani'],false,['lunch','dinner'],['wedding','dinner'],['muslim']),
I('Chapli Kebab Platter','main',['Pakistani'],false,['lunch','dinner'],['wedding','dinner'],['muslim']),
I('Aloo Gosht','main',['Pakistani','North Indian'],false,['lunch','dinner'],['wedding','dinner'],['muslim','hindu']),
I('Ilish Bhapa (Steamed Hilsa)','main',['Bangladeshi'],false,['lunch','dinner'],['wedding','dinner'],['hindu','muslim','christian']),
I('Kosha Mangsho (Bengali Mutton)','main',['Bangladeshi'],false,['lunch','dinner'],['wedding','dinner']),
I('Chingri Malai Curry','main',['Bangladeshi'],false,['lunch','dinner'],['wedding','dinner'],['hindu','christian']),
I('Puran Poli Thali Main','main',['Marathi'],true,['lunch'],['wedding','lunch']),
I('Kolhapuri Chicken','main',['Marathi'],false,['lunch','dinner'],['wedding','dinner']),
I('Chicken Chettinad','main',['Tamil'],false,['lunch','dinner'],['wedding','dinner']),
I('Meen Kuzhambu (Tamil Fish Curry)','main',['Tamil'],false,['lunch','dinner'],['wedding','dinner'],['hindu','christian']),
I('Kara Kuzhambu','main',['Tamil'],true,['lunch','dinner'],['wedding','lunch']),
I('Hakka Noodles & Vegetable Fried Rice','main',['Chinese'],true,['lunch','dinner'],['wedding','dinner','sangeet']),
I('Stir-Fried Chili Chicken','main',['Chinese','Fusion'],false,['lunch','dinner'],['wedding','dinner']),
I('Peach-Pepper & Cheese Veggie Enchiladas','main',['Mexican'],true,['lunch','dinner'],['wedding','dinner','sweet16']),
I('Chicken Quesadilla','main',['Mexican'],false,['lunch','dinner'],['wedding','dinner','sweet16']),
I('Spiced Veggie Quesadilla, Grilled to Order','main',['Mexican'],true,['lunch','dinner'],['wedding','dinner','sweet16']),
I('Pasta Station Live — Alfredo, Marinara, Hot Indian Sauce','main',['Italian','Fusion'],true,['lunch','dinner'],['wedding','dinner','sweet16']),
I('Tandoori Chicken Penne with Parmesan & Olives','main',['Italian','Fusion'],false,['lunch','dinner'],['wedding','dinner']),
I('Marrakech Salmon on Melted Tomatoes with Tahini','main',['Mediterranean'],false,['lunch','dinner'],['wedding','dinner']),
I('Tangier Vegetable Platter','main',['Mediterranean'],true,['lunch','dinner'],['wedding','dinner']),
I('BBQ Sliders with House Slaw','main',['American'],false,['lunch','dinner'],['sweet16','birthday','anniversary'],['hindu','christian']),
I('Mac & Cheese Bar','main',['American'],true,['lunch','dinner'],['sweet16','birthday']),

/* ================= RICE ================= */
I('Vegetable Biryani','rice',['North Indian','South Indian'],true,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Chicken Biryani','rice',['North Indian','South Indian'],false,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Hyderabadi Dhum Biryani Live','rice',['Telugu/Andhra'],false,['lunch','dinner'],['wedding','dinner','sangeet']),
I('Sindhi Pulao','rice',['Sindhi'],true,['lunch','dinner'],['wedding','lunch']),
I('Basmati Peas Pilaf','rice',['North Indian'],true,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Jeera Rice Pilaf','rice',['North Indian'],true,['lunch','dinner'],['wedding','lunch','dinner'],null,true),
I('Lemon Rice / Tomato Rice / Curd Rice','rice',['South Indian','Tamil'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Pulihora (Tamarind Rice)','rice',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Spicy Noodle Biryani','rice',['Fusion'],true,['lunch','dinner'],['wedding','dinner']),
I('Bisi Bele Bath','rice',['South Indian'],true,['lunch','dinner'],['wedding','lunch']),
I('Sindhi Beh Pulao (Lotus Stem Rice)','rice',['Sindhi'],true,['lunch','dinner'],['wedding','lunch']),
I('Kolhapuri Masale Bhaat','rice',['Marathi'],true,['lunch','dinner'],['wedding','lunch']),
I('Kacchi Biryani, Pakistani Style','rice',['Pakistani'],false,['lunch','dinner'],['wedding','dinner'],['muslim']),
I('Bhuna Khichuri Rice','rice',['Bangladeshi'],true,['lunch','dinner'],['wedding','lunch']),
I('Curd Rice with Tempering','rice',['Tamil'],true,['lunch','dinner'],['wedding','lunch'],null,true),

/* ================= BREAD ================= */
I('Freshly Made Chapati / Poori','bread',['North Indian'],true,['lunch','dinner'],ALL_EVENTS,null,true),
I('Freshly Baked Naan','bread',['North Indian'],true,['lunch','dinner'],ALL_EVENTS,null,true),
I('Malabar Paratha','bread',['Kerala'],true,['lunch','dinner'],['wedding','dinner'],null,true),
I('Freshly Made Batura','bread',['Punjabi'],true,['lunch'],['wedding','lunch'],null,true),
I('Bhakri (Marathi Flatbread)','bread',['Marathi'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Sheermal, Pakistani Style','bread',['Pakistani'],true,['lunch','dinner'],['wedding','dinner'],['muslim'],true),
I('Luchi (Bengali Puri)','bread',['Bangladeshi'],true,['breakfast','lunch'],['breakfast','wedding'],null,true),
I('Rumali Roti','bread',['North Indian','Pakistani'],true,['lunch','dinner'],ALL_EVENTS,null,true),

/* ================= DESSERT ================= */
I('Rasmalai in Cocktail Glasses with Pistachio & Mint','dessert',['North Indian'],true,['lunch','dinner'],['wedding','dinner','anniversary'],null,true),
I('Shrikhand in Traditional Mudka','dessert',['Gujarati','Marathi'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Assorted Bengali Mithai Platter','dessert',['Bangladeshi'],true,['lunch','dinner'],['wedding','dinner'],null,true),
I('Live Jalebi with Rabri Station','dessert',['North Indian'],true,['dinner','snacks'],['wedding','sangeet','mehndi']),
I('Chocolate Fondue Bar — Marshmallows, Pretzels, Fruit','dessert',['American','Fusion'],true,['dinner','snacks'],['wedding','sweet16','birthday']),
I('Halwa Bar — Bombay, Gajar, Badam','dessert',['North Indian'],true,['dinner'],['wedding','dinner','anniversary']),
I('Cardamom Coffee Mousse with Chocolate Curls','dessert',['Fusion'],true,['dinner'],['wedding','anniversary']),
I('Pistachio Stick Kulfi','dessert',['North Indian'],true,['lunch','dinner','snacks'],['wedding','dinner','sweet16'],null,true),
I('Boondi Laddu','dessert',['South Indian','Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Boorelu','dessert',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Ariselu','dessert',['Telugu/Andhra'],true,['lunch','dinner'],['wedding','lunch']),
I('Kaju Katli','dessert',['North Indian'],true,['lunch','dinner'],['wedding','lunch','anniversary'],null,true),
I('Handmade French Macaroon Tower & Petit Fours','dessert',['Italian','Fusion'],true,['dinner'],['wedding','dinner','anniversary']),
I('Mango Crème Brûlée with Fresh Berries','dessert',['Italian','Fusion'],true,['dinner'],['wedding','dinner','anniversary']),
I('Seasonal Fresh Fruit with Vanilla Ice Cream','dessert',['American'],true,['lunch','dinner','breakfast'],ALL_EVENTS,null,true),
I('Baked Bundi Gulab Jamun with Saffron','dessert',['North Indian'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Modak (Marathi Steamed Dumplings)','dessert',['Marathi'],true,['lunch','dinner'],['wedding','lunch']),
I('Sheer Khurma','dessert',['Pakistani'],true,['breakfast','lunch','dinner'],['wedding','breakfast'],['muslim']),
I('Roshogolla','dessert',['Bangladeshi'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Payasam, Kerala Style','dessert',['Kerala'],true,['lunch','dinner'],['wedding','lunch'],null,true),

/* ================= BEVERAGE ================= */
I('Freshly Brewed Masala Chai','beverage',['North Indian'],true,['breakfast','lunch','dinner','snacks'],ALL_EVENTS,null,true),
I('Madras Filter Coffee','beverage',['South Indian','Tamil'],true,['breakfast','lunch','dinner','snacks'],ALL_EVENTS,null,true),
I('Mango, Strawberry & Sweet Lassi (Butler-Passed)','beverage',['North Indian'],true,['lunch','dinner','ceremony'],ALL_EVENTS,null,true),
I('Chocolate Fondue Fruit Skewers (bev-side)','beverage',['Fusion'],true,['snacks'],['sweet16','birthday']),
I('Solkadhi (Kokum Cooler)','beverage',['Marathi'],true,['lunch','dinner'],['wedding','lunch'],null,true),
I('Jaljeera','beverage',['North Indian'],true,['breakfast','lunch','dinner'],ALL_EVENTS,null,true),
I('Rooh Afza Sharbat','beverage',['Pakistani'],true,['breakfast','lunch','dinner'],ALL_EVENTS,['muslim','hindu'],true),
I('Borhani (Bengali Spiced Yogurt Drink)','beverage',['Bangladeshi'],true,['lunch','dinner'],['wedding','lunch'],null,true),

/* ================= LIVE STATIONS ================= */
I('Chaat Station — Papdi, Bhel, Pani Poori, Chutney Bar','station',['North Indian'],true,['snacks','dinner','lunch'],['wedding','sangeet','mehndi']),
I('Hyderabadi Biryani Station — Choose Meat, Spice & Veg','station',['Telugu/Andhra'],false,['lunch','dinner'],['wedding','dinner','sangeet']),
I('South Indian Dosa Station','station',['South Indian','Tamil'],true,['breakfast','lunch','dinner'],['wedding','breakfast','dinner']),
I('Beijing Bites Indo-Chinese Live Wok','station',['Chinese'],true,['dinner','snacks'],['wedding','sangeet']),
I('Fiesta Mexicana Taco & Nacho Live','station',['Mexican'],true,['dinner','snacks'],['wedding','sangeet','sweet16']),
I("Viva l'Italia Pasta & Caesar Live",'station',['Italian'],true,['dinner'],['wedding','dinner']),
I('Moroccan Mezze Station — Hummus, Falafel, Pita','station',['Mediterranean'],true,['dinner','snacks'],['wedding','dinner']),
I('Halwa & Dessert Live Station with Ice Cream Bar','station',['North Indian'],true,['dinner'],['wedding','dinner','anniversary']),
I('Portable Tandoor & Kebab Live Grill','station',['North Indian'],false,['dinner'],['wedding','dinner']),
I('Kati Roll Live Station — Chicken, Paneer, Manchurian','station',['Fusion'],true,['cocktail','snacks'],['wedding','cocktail']),
I('Paan Display','station',['North Indian'],true,['dinner'],['wedding','lunch']),
I('North Indian Live Omelet Station','station',['North Indian'],false,['breakfast'],['breakfast','wedding'],['hindu','christian']),
I('Andhra Live Dosa & Pesarattu Station','station',['Telugu/Andhra'],true,['breakfast','lunch'],['breakfast','wedding']),
I('Karachi Grill Live BBQ Station','station',['Pakistani'],false,['dinner'],['wedding','dinner'],['muslim']),
I('Bengali Fish Fry Live Station','station',['Bangladeshi'],false,['dinner'],['wedding','dinner'],['hindu','muslim','christian']),
];

module.exports = { items };
